version: '3.4'

x-tessera-def:
  &tessera-def
  image: quorumengineering/tessera:latest
  expose:
    - 9081
    - 9101
    - 9000
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:9000/upcheck"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 100s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir -p /var/log/tessera/;
      mkdir -p /opt/tessera/;
      mkdir -p /opt/keys/;
      cat << EOF > /opt/tessera/tessera.json
        {
          "mode": "orion",
          "useWhiteList": false,
          "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:/opt/tessera/target/h2/tessera;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
          },
          "serverConfigs":[
              {
                  "app":"ThirdParty",
                  "enabled": true,
                  "serverAddress": "http://$$(hostname -i):9081",
                  "communicationType" : "REST",
                  "cors" : {
                      "allowedMethods" : ["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"],
                      "allowedOrigins" : "*",
                      "allowedHeaders" : ["content-type"],
                      "allowCredentials" : true
                  }
              },
              {
                  "app":"Q2T",
                  "enabled": true,
                  "serverAddress": "http://$$(hostname -i):9101"
              },
              {
                  "app":"P2P",
                  "enabled": true,
                  "communicationType" : "REST",
                  "serverAddress":"http://$$(hostname -i):9000",
                  "sslConfig": {
                      "tls": "OFF"
                  }
              }
          ],
          "peer": [
              {
                  "url": "http://tessera1:9000"
              },
              {
                  "url": "http://tessera2:9000"
              },
              {
                  "url": "http://tessera3:9000"
              },
              {
                  "url": "http://tessera4:9000"
              }
          ],
          "keys": {
              "passwords": [],
              "keyData": [
                  {
                      "privateKeyPath": "/opt/keys/tessera.key",
                      "publicKeyPath": "/opt/keys/tessera.pub"
                  }
              ]
          },
          "alwaysSendTo": []
        }
      EOF
      cat /opt/tessera/tessera.json;
      /tessera/bin/tessera -configfile /opt/tessera/tessera.json 2>&1 | tee -a /var/log/tessera/tessera-$$(hostname -i).log

networks:
  ssd-besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.229.0/24

services:
  tessera1:
    container_name: tessera1
    hostname: tessera1
    << : *tessera-def
    volumes:
      - ./data/tessera1:/opt/tessera
      - ./config/node1:/opt/keys
      - ./logs/tessera:/var/log/tessera
    ports:
      - 9081:9081
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.21

  tessera2:
    container_name: tessera2
    hostname: tessera2
    << : *tessera-def
    volumes:
      - ./data/tessera2:/opt/tessera
      - ./config/node2:/opt/keys
      - ./logs/tessera:/var/log/tessera
    ports:
      - 9082:9081
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.22

  tessera3:
    container_name: tessera3
    hostname: tessera3
    << : *tessera-def
    volumes:
      - ./data/tessera3:/opt/tessera
      - ./config/node3:/opt/keys
      - ./logs/tessera:/var/log/tessera
    ports:
      - 9083:9081
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.23

  tessera4:
    container_name: tessera4
    hostname: tessera4
    << : *tessera-def
    volumes:
      - ./data/tessera4:/opt/tessera
      - ./config/node4:/opt/keys
      - ./logs/tessera:/var/log/tessera
    ports:
      - 9084:9081
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.24

  besu1:
    container_name: besu1
    hostname: besu1
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/log/besu/;
        mkdir -p /opt/besu/config/;
        /opt/besu/bin/besu --privacy-url=http://tessera1:9101 \
          --config-file=/opt/besu/config/config.toml \
          2>&1 | tee /var/log/besu/besu-$$(hostname -i).log
    volumes:
      - ./config/genesis.json:/opt/besu/config/genesis.json
      - ./config/config.toml:/opt/besu/config/config.toml
      - ./config/node1/besu.key:/opt/besu/config/besu.key
      - ./config/node1/tessera.pub:/opt/besu/config/tessera.pub
      - ./data/besu1:/opt/besu/data
      - ./logs/besu:/var/log/besu
    depends_on:
      - tessera1
    ports:
      - 8545:8545
      - 9545:8546
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.101

  besu2:
    container_name: besu2
    hostname: besu2
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/log/besu/;
        mkdir -p /opt/besu/config/;
        /opt/besu/bin/besu --privacy-url=http://tessera2:9101 \
          --config-file=/opt/besu/config/config.toml \
          2>&1 | tee /var/log/besu/besu-$$(hostname -i).log
    volumes:
      - ./config/genesis.json:/opt/besu/config/genesis.json
      - ./config/config.toml:/opt/besu/config/config.toml
      - ./config/node2/besu.key:/opt/besu/config/besu.key
      - ./config/node2/tessera.pub:/opt/besu/config/tessera.pub
      - ./data/besu2:/opt/besu/data
      - ./logs/besu:/var/log/besu
    depends_on:
      - besu1
      - tessera2
    ports:
      - 8546:8545
      - 9546:8546
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.102
    
  besu3:
    container_name: besu3
    hostname: besu3
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/log/besu/;
        mkdir -p /opt/besu/config/;
        /opt/besu/bin/besu --privacy-url=http://tessera3:9101 \
          --config-file=/opt/besu/config/config.toml \
          2>&1 | tee /var/log/besu/besu-$$(hostname -i).log
    volumes:
      - ./config/genesis.json:/opt/besu/config/genesis.json
      - ./config/config.toml:/opt/besu/config/config.toml
      - ./config/node3/besu.key:/opt/besu/config/besu.key
      - ./config/node3/tessera.pub:/opt/besu/config/tessera.pub
      - ./data/besu3:/opt/besu/data
      - ./logs/besu:/var/log/besu
    depends_on:
      - besu1
      - tessera3
    ports:
      - 8547:8545
      - 9547:8546
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.103

  besu4:
    container_name: besu4
    hostname: besu4
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - |
        mkdir -p /var/log/besu/;
        mkdir -p /opt/besu/config/;
        /opt/besu/bin/besu --privacy-url=http://tessera4:9101 \
          --config-file=/opt/besu/config/config.toml \
          2>&1 | tee /var/log/besu/besu-$$(hostname -i).log
    volumes:
      - ./config/genesis.json:/opt/besu/config/genesis.json
      - ./config/config.toml:/opt/besu/config/config.toml
      - ./config/node4/besu.key:/opt/besu/config/besu.key
      - ./config/node4/tessera.pub:/opt/besu/config/tessera.pub
      - ./data/besu4:/opt/besu/data
      - ./logs/besu:/var/log/besu
    depends_on:
      - besu1
      - tessera4
    ports:
      - 8548:8545
      - 9548:8546
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.104

  explorer:
    container_name: explorer
    hostname: explorer
    image: consensys/quorum-explorer:latest
    entrypoint:
    - /bin/sh
    - -c
    - |
      cat << EOF > /app/config.json
        {
          "algorithm": "qbft",
          "nodes": [
            {
              "name": "besu1",
              "client": "besu",
              "rpcUrl": "http://besu1:8545",
              "privateTxUrl": "http://tessera1:9081",
              "privateKey": "$$(cat /app/config/node1/besu.address)",
              "accountAddress": "$$(cat /app/config/node1/besu.key)
            },
            {
              "name": "besu2",
              "client": "besu",
              "rpcUrl": "http://besu1:8545",
              "privateTxUrl": "http://tessera2:9081",
              "privateKey": "$$(cat /app/config/node2/besu.address)",
              "accountAddress": "$$(cat /app/config/node2/besu.key)
            },
            {
              "name": "besu1",
              "client": "besu",
              "rpcUrl": "http://besu3:8545",
              "privateTxUrl": "http://tessera3:9081",
              "privateKey": "$$(cat /app/config/node3/besu.address)",
              "accountAddress": "$$(cat /app/config/node3/besu.key)
            },
            {
              "name": "besu4",
              "client": "besu",
              "rpcUrl": "http://besu4:8545",
              "privateTxUrl": "http://tessera4:9081",
              "privateKey": "$$(cat /app/config/node4/besu.address)",
              "accountAddress": "$$(cat /app/config/node4/besu.key)
            }
          ]
        }
      EOF
      cat /app/config.json;
      cd /app;
      npm i;
      npm start
    volumes:
      - ./config:/app/config
      - ./config/explorer/env.production:/app/.env.production
    depends_on:
      - besu1
    ports:
      - 8080:25000
    networks:
      ssd-besu-network:
        ipv4_address: 172.16.229.50